---
# Tasks specific for Centos7 based AWS systems

- name: "Install packages"
  package: name={{ item }} state=present
  with_items:
   - libsemanage-python
   - libselinux-python
  when: ansible_distribution == "Amazon" or ansible_distribution == "CentOS"

- name: "Enable Nginx repo"
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644

- name: "Ensure Nginx is installed"
  yum:
    name: "nginx"
    state: installed

- name: "Add grafana repository"
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
    owner: root
    group: root
    mode: 0644
  become: true

- set_fact: grafana_release='grafana={{grafana_version}}'

- name: "Install Grafana version - {{grafana_version}}"
  yum: name="{{grafana_release}}"
  when: grafana_version != "latest"
  notify:
    - grafana restart

- name: "Install Latest version of Grafana"
  yum: name="grafana"
  when: grafana_version == "latest"
  notify:
  - grafana restart

- name: "CentOS/Amazon | Compile Nginx configuration"
  template: src=nginx.conf.j2 dest={{nginx_dir|default('/etc/nginx')}}/conf.d/default.conf
  notify:  nginx reload

- name: "Amazon | Compile nginx.conf"
  template: src=amz.conf.j2 dest=/etc/nginx/nginx.conf
  notify:  nginx reload
  when: ansible_distribution == "Amazon"

- name: "Enable Nginx service"
  service: name=nginx enabled=yes

- name: "CentOS | Configure SELinux to allow httpd "
  seboolean: name=httpd_can_network_connect state=yes persistent=yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

- name: "Install firewalld"
  action: yum name=firewalld state=installed

- name: "Enable firewalld on system reboot"
  service: name=firewalld enabled=yes

- name: "Start service firewalld, if not started"
  service:
    name: firewalld
    state: started

- name: "Enable SELinux"
  selinux:
    policy: targeted
    state: enforcing
